# Generated by Django 4.2.7 on 2023-11-12 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=1000, verbose_name='')),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('tps', models.DecimalField(decimal_places=25, max_digits=50)),
                ('latency', models.DecimalField(decimal_places=25, max_digits=50)),
                ('stddev', models.DecimalField(decimal_places=25, max_digits=50)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShowGraph.files')),
            ],
        ),
    ]
